name: Continuous integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: gradle:jdk11
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd 2021-offseason
          ./gradlew downloadAll
          ./gradlew jar
  format:
    name: Google Java Format
    # You may pin to the exact commit or the version.
    # uses: axel-op/googlejavaformat-action@d4a4c91b6e34fc80edbba7a029651e8951b44f91
    uses: axel-op/googlejavaformat-action@3.5.0
    # with:
      # Arguments for the Google Java Format executable
      # args: # optional, default is --replace
      # Pattern to match files to be formatted
      # files: # optional, default is **/*.java
      # Set to true to not commit the changes
      # skipCommit: # optional, default is false
      # Version of Google Java Format to use
      # version: # optional
      # Recommended on MacOS machines
      # githubToken: # optional
      # Commit message
      # commitMessage: # optional, default is Google Java Format
